-- Update Menu Script
-- Run this in your Supabase SQL Editor

-- 1. Delete all existing categories (this will cascade and delete menu items too)
DELETE FROM categories;

-- 2. Insert Categories
INSERT INTO categories (name, sort_order) VALUES
('NOODLES', 1),
('RICE', 2),
('CHILLI POTATOES', 3),
('BURGER', 4),
('SANDWICH', 5),
('SPRING ROLLS', 6),
('MOMOS', 7),
('FRIES', 8),
('PASTA', 9),
('MAGGI', 10),
('PIZZA', 11),
('MOJITO', 12),
('COFFEE', 13),
('SHAKES', 14),
('CHAI', 15);

-- 3. Insert Menu Items
INSERT INTO menu_items (category_id, name, price, variants, is_available, presentation_type)
VALUES
((SELECT id FROM categories WHERE name = 'NOODLES'), 'Veg Noodles', 59, '[{"id":"half","name":"Half","priceDelta":0},{"id":"full","name":"Full","priceDelta":40}]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'NOODLES'), 'Singapore Noodles', 69, '[{"id":"half","name":"Half","priceDelta":0},{"id":"full","name":"Full","priceDelta":50}]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'NOODLES'), 'Chilli Garlic Noodles', 79, '[{"id":"half","name":"Half","priceDelta":0},{"id":"full","name":"Full","priceDelta":50}]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'NOODLES'), 'Hakka Noodles', 79, '[{"id":"half","name":"Half","priceDelta":0},{"id":"full","name":"Full","priceDelta":50}]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'RICE'), 'Fried Rice', 59, '[{"id":"half","name":"Half","priceDelta":0},{"id":"full","name":"Full","priceDelta":60}]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'RICE'), 'Paneer Fried Rice', 79, '[{"id":"half","name":"Half","priceDelta":0},{"id":"full","name":"Full","priceDelta":50}]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'CHILLI POTATOES'), 'Chilli Potatoes', 69, '[{"id":"half","name":"Half","priceDelta":0},{"id":"full","name":"Full","priceDelta":60}]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'CHILLI POTATOES'), 'Honey Chilli Potatoes', 79, '[{"id":"half","name":"Half","priceDelta":0},{"id":"full","name":"Full","priceDelta":60}]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'BURGER'), 'Veg Burger', 49, '[]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'BURGER'), 'Paneer Burger', 59, '[]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'BURGER'), 'Cheese Burger', 69, '[]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'BURGER'), 'Loaded Burger', 99, '[]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'SANDWICH'), 'Veg Sandwich', 59, '[]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'SANDWICH'), 'Cheese Sandwich', 69, '[]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'SANDWICH'), 'Paneer Sandwich', 79, '[]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'SANDWICH'), 'Cheese Paneer Sandwich', 99, '[]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'SPRING ROLLS'), 'Veg Spring Rolls', 79, '[]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'SPRING ROLLS'), 'Paneer Spring Rolls', 99, '[]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'MOMOS'), 'Veg Steam Momo', 49, '[{"id":"4pcs","name":"4 pcs","priceDelta":0},{"id":"8pcs","name":"8 pcs","priceDelta":20}]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'MOMOS'), 'Veg Fried Momo', 49, '[{"id":"4pcs","name":"4 pcs","priceDelta":0},{"id":"8pcs","name":"8 pcs","priceDelta":20}]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'MOMOS'), 'Veg Kurkure Momo', 69, '[{"id":"4pcs","name":"4 pcs","priceDelta":0},{"id":"8pcs","name":"8 pcs","priceDelta":30}]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'MOMOS'), 'Tandoori Momo', 79, '[{"id":"4pcs","name":"4 pcs","priceDelta":0},{"id":"8pcs","name":"8 pcs","priceDelta":40}]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'MOMOS'), 'Gravy Momo', 79, '[{"id":"4pcs","name":"4 pcs","priceDelta":0},{"id":"8pcs","name":"8 pcs","priceDelta":50}]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'MOMOS'), 'Paneer Kurkure Momo', 79, '[{"id":"4pcs","name":"4 pcs","priceDelta":0},{"id":"8pcs","name":"8 pcs","priceDelta":30}]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'MOMOS'), 'Paneer Steam Momo', 59, '[{"id":"4pcs","name":"4 pcs","priceDelta":0},{"id":"8pcs","name":"8 pcs","priceDelta":20}]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'MOMOS'), 'Paneer Fried Momo', 59, '[{"id":"4pcs","name":"4 pcs","priceDelta":0},{"id":"8pcs","name":"8 pcs","priceDelta":20}]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'MOMOS'), 'Paneer Tandoori Momo', 89, '[{"id":"4pcs","name":"4 pcs","priceDelta":0},{"id":"8pcs","name":"8 pcs","priceDelta":50}]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'FRIES'), 'Salted Fries', 50, '[]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'FRIES'), 'Peri Peri Fries', 60, '[]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'FRIES'), 'Cheese Fries', 90, '[]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'PASTA'), 'White Sauce Pasta', 150, '[]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'PASTA'), 'Red Sauce Pasta', 150, '[]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'PASTA'), 'Mix Sauce Pasta', 170, '[]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'MAGGI'), 'Plain Maggi', 40, '[]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'MAGGI'), 'Veg Maggi', 50, '[]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'MAGGI'), 'Cheese Paneer Maggi', 70, '[]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'MAGGI'), 'Cheese Maggi', 60, '[]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'PIZZA'), 'Onion Pizza', 69, '[{"id":"S","name":"S","priceDelta":0},{"id":"M","name":"M","priceDelta":70},{"id":"L","name":"L","priceDelta":160}]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'PIZZA'), 'Tomato Pizza', 69, '[{"id":"S","name":"S","priceDelta":0},{"id":"M","name":"M","priceDelta":70},{"id":"L","name":"L","priceDelta":160}]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'PIZZA'), 'Sweet Corn Pizza', 79, '[{"id":"S","name":"S","priceDelta":0},{"id":"M","name":"M","priceDelta":70},{"id":"L","name":"L","priceDelta":160}]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'PIZZA'), 'Paneer Pizza', 79, '[{"id":"S","name":"S","priceDelta":0},{"id":"M","name":"M","priceDelta":70},{"id":"L","name":"L","priceDelta":160}]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'PIZZA'), 'Onion + Capsicum Pizza', 79, '[{"id":"S","name":"S","priceDelta":0},{"id":"M","name":"M","priceDelta":70},{"id":"L","name":"L","priceDelta":160}]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'PIZZA'), 'Onion + Corn Pizza', 89, '[{"id":"S","name":"S","priceDelta":0},{"id":"M","name":"M","priceDelta":70},{"id":"L","name":"L","priceDelta":160}]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'PIZZA'), 'Onion + Paneer Pizza', 99, '[{"id":"S","name":"S","priceDelta":0},{"id":"M","name":"M","priceDelta":70},{"id":"L","name":"L","priceDelta":150}]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'PIZZA'), 'Paneer + Corn Pizza', 99, '[{"id":"S","name":"S","priceDelta":0},{"id":"M","name":"M","priceDelta":70},{"id":"L","name":"L","priceDelta":150}]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'PIZZA'), 'Rectangular Onion + Capsicum', 139, '[]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'PIZZA'), 'Rectangular Onion + Corn', 149, '[]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'PIZZA'), 'Rectangular Onion + Paneer', 159, '[]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'PIZZA'), 'Rectangular Paneer + Corn', 159, '[]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'MOJITO'), 'Lime Soda', 60, '[]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'MOJITO'), 'Black Current', 70, '[]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'MOJITO'), 'Mint', 60, '[]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'MOJITO'), 'Virgin Mojito', 70, '[]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'COFFEE'), 'Cold Coffee Classic', 59, '[]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'COFFEE'), 'Hazelnut Coffee', 69, '[]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'COFFEE'), 'Caramel Coffee', 79, '[]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'SHAKES'), 'Cake & Coffee Shake', 99, '[]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'SHAKES'), 'Protein Shake', 89, '[]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'SHAKES'), 'KitKat Shake', 79, '[]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'SHAKES'), 'Oreo Shake', 79, '[]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'CHAI'), 'Chai', 20, '[]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'CHAI'), 'Adrak Chai', 20, '[]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'CHAI'), 'Elaichi Chai', 30, '[]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'CHAI'), 'Kesar Chai', 40, '[]'::jsonb, true, 'plate'),
((SELECT id FROM categories WHERE name = 'CHAI'), 'Masala Chai', 30, '[]'::jsonb, true, 'plate');
